# Generated by Django 2.1.4 on 2018-12-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20181204_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('0', 'Image'), ('1', 'Video')], default='0', max_length=1),
        ),
    ]
