# Generated by Django 2.1.4 on 2018-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_media_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
